# Generated by Django 4.1.5 on 2023-02-15 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата обновления карточки')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Поле для коментария')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utv_smeta.comments')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='TableProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_client', models.FloatField(null=True, verbose_name='Цена для клиента')),
                ('planned_cost', models.FloatField(null=True, verbose_name='Плановая себестоимость')),
                ('cost', models.FloatField(null=True, verbose_name='Фактическая себестоимость')),
                ('planned_salary', models.FloatField(null=True, verbose_name='Плановая зарплата')),
                ('salary', models.FloatField(null=True, verbose_name='Фактическая зарплата')),
                ('planed_actors_salary', models.FloatField(null=True, verbose_name='Плановая зарплата актёрам')),
                ('actors_salary', models.FloatField(null=True, verbose_name='Зарплата актёрам')),
                ('planned_taxes_FOT', models.FloatField(null=True, verbose_name='Плановые налоги с ФОТ')),
                ('taxes_FOT', models.FloatField(null=True, verbose_name='Фактические налоги с ФОТ')),
                ('planned_other_expenses', models.FloatField(null=True, verbose_name='Плановые Покупка реквизита для организации съемочного процесса/ Непредвиденные расходы')),
                ('other_expenses', models.FloatField(null=True, verbose_name='Плановые Покупка реквизита для организации съемочного процесса/ Непредвиденные расходы')),
                ('planned_buying_music', models.FloatField(null=True, verbose_name='Плановая покупка музыки')),
                ('buying_music', models.FloatField(null=True, verbose_name='Фактическая покупка музыки')),
                ('planned_travel_expenses', models.FloatField(null=True, verbose_name='Плановые командировачные расходы')),
                ('travel_expenses', models.FloatField(null=True, verbose_name='Фактические командировачные расходы')),
                ('planned_fare', models.FloatField(null=True, verbose_name='Плановые транспортные расходы')),
                ('fare', models.FloatField(null=True, verbose_name='Фактические транспортные расходы')),
                ('planned_general_expenses', models.FloatField(null=True, verbose_name='Плановые общехозяйственные расходы')),
                ('general_expenses', models.FloatField(null=True, verbose_name='Фактические общехозяйственные расходы')),
                ('planned_profit', models.FloatField(null=True, verbose_name='Плановая прибыль')),
                ('profit', models.FloatField(null=True, verbose_name='Фактическая прибыль')),
                ('planned_profitability', models.FloatField(null=True, verbose_name='Плановая рентабельность')),
                ('profitability', models.FloatField(null=True, verbose_name='Фактическая рентабельность')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания таблицы')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Дата обновления таблицы')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_time', models.IntegerField(default=0, verbose_name='Фактическое время')),
                ('scheduled_time', models.IntegerField(default=0, verbose_name='Плановое время')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания работы')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата обновления работы')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utv_smeta.cards')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utv_smeta.worker')),
            ],
        ),
        migrations.CreateModel(
            name='TableCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utv_smeta.cards')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utv_smeta.tableproject')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(null=True, verbose_name='Заработок в час')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeerate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utv_smeta.cards')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utv_smeta.comments')),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='comment',
            field=models.ManyToManyField(through='utv_smeta.CommentsCards', to='utv_smeta.comments'),
        ),
        migrations.AddField(
            model_name='cards',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='CardEvent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cards',
            name='table',
            field=models.ManyToManyField(through='utv_smeta.TableCards', to='utv_smeta.tableproject'),
        ),
        migrations.AddField(
            model_name='cards',
            name='worker',
            field=models.ManyToManyField(through='utv_smeta.WorkerCards', to='utv_smeta.worker'),
        ),
    ]
