# Generated by Django 4.1.5 on 2023-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utv_smeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_time', models.TimeField(default=0, verbose_name='Фактическое время')),
                ('scheduled_time', models.TimeField(default=0, verbose_name='Плановое время')),
            ],
        ),
    ]
