# Generated by Django 4.1.5 on 2023-05-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utv_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableExcel',
        ),
    ]
