# Generated by Django 4.1.5 on 2023-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utv_api', '0004_categoryevent_event_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Добавить в архив'),
        ),
    ]
