# Generated by Django 4.1.5 on 2023-03-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utv_api', '0005_cards_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='performers',
            field=models.ManyToManyField(related_name='performers', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
