# Generated by Django 4.1.5 on 2023-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utv_api', '0006_event_performers_alter_event_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryevent',
            options={'verbose_name': 'Категория события', 'verbose_name_plural': 'Категории событий'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие в календаре', 'verbose_name_plural': 'События в календаре'},
        ),
        migrations.AddField(
            model_name='event',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
