name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Migration
      run: |
        make migrate
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run Lint
      run: |
        make lint
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CC_TEST_REPORTER_ID: 3d736fed470d0631549e662fe73d3c7d6542de959aeeff3a45061d6556be3e0e
      with:
        coverageCommand: make coverage-xml
        debug: true
        
